package com.example.demo.dto.enums;

public enum TaskName {
    TEST_COMPUTE_PI,
    CLASSIFICATION_DECISION_TREE,
    CLASSIFICATION_RANDOM_FOREST,
    CLASSIFICATION_LOGISTIC_REGRESSION,
    CLASSIFICATION_NAIVE_BAYES,
    CLASSIFICATION_LINEAR_SVM,
    ASSOCIATIONS_FP_GROWTH,
    CLUSTERING_K_MEANS_SPARK_ML,
    CLUSTERING_K_MEANS_IMPLEMENTATION
}
